---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cryptpad-data
  namespace: cryptpad
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50G
  storageClassName: cephfs