---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptpadapi
  namespace: cryptpad
spec:
  selector:
    matchLabels:
      app: cryptpadapi
  replicas: 1
  template:
    metadata:
      labels:
        app: cryptpadapi
    spec:
      containers:
        - name: cryptpad-api
          image: promasu/cryptpad:3.3.0-2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: config
              mountPath: /cryptpad/config
            - name: data
              mountPath: /cryptpad/data
      volumes:
        - name: config
          configMap:
            name: padapiconfig
        - name: data
          persistentVolumeClaim:
            claimName: cryptpad-data
      initContainers:
        - name: take-data-dir-ownership
          image: busybox
          command:
            - chown
            - 4001:4001
            - /srv/data
          volumeMounts:
            - name: data
              mountPath: /srv/data
---
apiVersion: v1
kind: Service
metadata:
  name: cryptpad-api-service
  namespace: cryptpad
spec:
  selector:
    app: cryptpadapi
  ports:
    - name: api
      port: 3000
      targetPort: 3000
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: cryptpad-api
  namespace: cryptpad
  generation: 1
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: padapi.piratenpartei.de
      http:
        paths:
          - path: /
            backend:
              serviceName: cryptpad-api-service
              servicePort: 3000
